<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <UseWPF>true</UseWPF>
    <Platforms>x86;x64</Platforms>
    <PlatformTarget Condition="'$(Platform)' == 'x86'">x86</PlatformTarget>
    <PlatformTarget Condition="'$(Platform)' != 'x86'">x64</PlatformTarget>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\..\..\..\SharpE\Addons\$(PlatformTarget)\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.118" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpEnviro\SharpEnviro.csproj" />
  </ItemGroup>

</Project>
